line-length = 120
target-version = "py311"

[lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "YTT",
    "ASYNC",
    "B",
    "A",
    "COM",
    "C4",
    "FA",
    "PIE",
    "PT",
    "RSE",
    "NPY",
    "PERF",
    "FURB",
]
ignore = ["E402", "E501", "COM812"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"typing.py" = ["F401"]
"*_pb2.py" = ["F401"]
